import type { Metadata } from 'next'
import './globals.css'
import MenuBar from '@/components/MenuBar'
import Footer from '@/components/Footer'
import { Montserrat } from 'next/font/google' 
import React from 'react'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat'
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} font-sans relative`}>
      <MenuBar/>
        {children}
      <Footer/>
      </body>
    </html>
  )
}
